server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /assets/img/ { expires 1y; add_header Cache-Control "public, immutable"; }
    location /assets/data/ { expires 5m; }
    location / { try_files $uri $uri/ /index.html; }
}
